name: radio
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  just_audio: ^0.7.5
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  flutter_spinkit: ^5.0.0
  marquee: ^2.1.0
  path_provider_ex: ^1.0.1
  flutter_file_manager: ^0.2.0
  permission_handler: ^8.0.1
  connectivity: ^3.0.6
  # url_launcher: ^6.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf

    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/TitilliumWeb-bold.ttf
          weight: 700